### ISSUE TITLE
Fresh install not loading correct Ruby

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/gitsh#320]
This is probably a macOS 10.12 issue, but I don't have Ruby 2.0 installed (at a global level) on my machine, so `gitsh` is failing to launch:

```
❯ gitsh
/usr/local/Cellar/gitsh/0.12/share/gitsh/ruby/lib/gitsh/line_editor.rb:1:in `require': dlopen(/usr/local/Cellar/gitsh/0.12/share/gitsh/ruby/lib/gitsh/line_editor_native.bundle, 9): Library not loaded: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib (LoadError)
  Referenced from: /usr/local/Cellar/gitsh/0.12/share/gitsh/ruby/lib/gitsh/line_editor_native.bundle
  Reason: image not found - /usr/local/Cellar/gitsh/0.12/share/gitsh/ruby/lib/gitsh/line_editor_native.bundle
        from /usr/local/Cellar/gitsh/0.12/share/gitsh/ruby/lib/gitsh/line_editor.rb:1:in `<top (required)>'
        from /usr/local/Cellar/gitsh/0.12/share/gitsh/ruby/lib/gitsh/environment.rb:3:in `require'
        from /usr/local/Cellar/gitsh/0.12/share/gitsh/ruby/lib/gitsh/environment.rb:3:in `<top (required)>'
        from /usr/local/Cellar/gitsh/0.12/share/gitsh/ruby/lib/gitsh/cli.rb:2:in `require'
        from /usr/local/Cellar/gitsh/0.12/share/gitsh/ruby/lib/gitsh/cli.rb:2:in `<top (required)>'
        from /usr/local/Cellar/gitsh/0.12/share/gitsh/ruby/gitsh.rb:6:in `require'
        from /usr/local/Cellar/gitsh/0.12/share/gitsh/ruby/gitsh.rb:6:in `<main>'
❯ ls /System/Library/Frameworks/Ruby.framework/Versions
2.3     Current
```

**Comment by georgebrock** [comment]
Thanks for reporting this, @gfontenot.

In theory it shouldn't have installed at all without finding a compatible version of Ruby to use.

One thing you could do to work around this for now is set the environment variable `RUBY` to the path of a Ruby 2+ binary when you install.

**Comment by gfontenot** [comment]
Ah, cool. In case anyone else hits this, I was able to get it built properly and running with:

```
❯ brew uninstall gitsh
❯ RUBY=/usr/bin/ruby brew install gitsh
```

**Comment by georgebrock** [comment]
Given that that works, the problem is probably with the Homebrew formula rather than the gitsh configuration script.
