### ISSUE TITLE
Won't install via homebrew

### ISSUE THREAD

**Issue by brbatwork** [thoughtbot/gitsh#329]
Used this for years on an older mac; now on my new mac I get:
```
[bbarbour@nebula1:~]$ brew install gitsh
==> Installing gitsh from thoughtbot/formulae
==> Downloading http://thoughtbot.github.io/gitsh/gitsh-0.12.tar.gz
Already downloaded: /Users/bbarbour/Library/Caches/Homebrew/gitsh-0.12.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/gitsh/0.12
Last 15 lines from /Users/bbarbour/Library/Logs/Homebrew/gitsh/01.configure:
You have to install development tools first.
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:541:in `try_link0'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:559:in `try_link'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:770:in `try_func'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:1004:in `block in have_library'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:947:in `block in checking_for'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:320:in `open'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:350:in `block in postpone'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:320:in `open'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:346:in `postpone'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:946:in `checking_for'
	from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/mkmf.rb:999:in `have_library'
	from extconf.rb:44:in `<main>'
configure: error: Failed to configure Ruby extension

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/thoughtbot/homebrew-formulae/issues

[bbarbour@nebula1:~]$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
[bbarbour@nebula1:~]$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```

What do I need to check to fix it?

**Comment by Ksantor** [comment]
Same here with
```
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin17]
```
and
```
Homebrew 1.7.6
Homebrew/homebrew-core (git revision 6dbf; last commit 2018-10-02)
```

**Comment by georgebrock** [comment]
Thanks for the reports. I haven't been able to reproduce on Mojave, but I'll see if I can find a Mac running High Sierra to try.

**Comment by ttbarnes** [comment]
I'm getting the same issue on Sierra 10.12.6 with `ruby 2.4.1`. Any workarounds?

**Comment by gfontenot** [comment]
I'm seeing this on a new machine using Sonoma 14.3 as well. It does seem like the configure script is ignoring the path somehow?

Install error:
```
==> ./configure --disable-silent-rules
Last 15 lines from /Users/fontenot/Library/Logs/Homebrew/gitsh/01.configure:
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:782:in `try_func'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
	from extconf.rb:44:in `<main>'
configure: error: Failed to configure Ruby extension
```

Ruby info:
```
❯ which ruby
/Users/fontenot/.asdf/shims/ruby
❯ ruby -v
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
```
