### ISSUE TITLE
Can not start gitsh not loading in MacOS Catalina

### ISSUE THREAD

**Issue by toshitapandey** [thoughtbot/gitsh#374]
I recently upgraded my MacOS to Catalina, and I can no more use gitsh. 
When I type gitsh, it gives me following error

```
$ gitsh
Traceback (most recent call last):
	5: from /usr/local/Cellar/gitsh/0.14/share/gitsh/ruby/gitsh.rb:6:in `<main>'
	4: from /usr/local/Cellar/gitsh/0.14/share/gitsh/ruby/gitsh.rb:6:in `require'
	3: from /usr/local/Cellar/gitsh/0.14/share/gitsh/ruby/lib/gitsh/environment.rb:3:in `<top (required)>'
	2: from /usr/local/Cellar/gitsh/0.14/share/gitsh/ruby/lib/gitsh/environment.rb:3:in `require'
	1: from /usr/local/Cellar/gitsh/0.14/share/gitsh/ruby/lib/gitsh/line_editor.rb:1:in `<top (required)>'
/usr/local/Cellar/gitsh/0.14/share/gitsh/ruby/lib/gitsh/line_editor.rb:1:in `require': dlopen(/usr/local/Cellar/gitsh/0.14/share/gitsh/ruby/lib/gitsh/line_editor_native.bundle, 0x0009): dependent dylib '/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/libruby.2.3.0.dylib' not found for '/usr/local/Cellar/gitsh/0.14/share/gitsh/ruby/lib/gitsh/line_editor_native.bundle' - /usr/local/Cellar/gitsh/0.14/share/gitsh/ruby/lib/gitsh/line_editor_native.bundle (LoadError)
```

**Comment by MiguelERuiz** [comment]
I have upgraded to Catalina too and I have the same problem.

**Comment by MiguelERuiz** [comment]
Finally I found a solution for this problem.

First of all, I uninstalled gitsh and then I tried to reinstall but with no success.

Then, I tried to run this command:

`$ xcode-select --install`

And then I installed gitsh like it is said in the README

`$ brew install gitsh`

And now it works fine, hope this solution works for you too @toshitapandey

**Comment by ttbarnes** [comment]
Thank you @MiguelERuiz this worked for me, even with a reinstall instead of fresh install 👍

`$ brew reinstall gitsh`
