### ISSUE TITLE
Can't install through brew

### ISSUE THREAD

**Issue by RafaelHovhannisyan** [thoughtbot/gitsh#388]
```
Last 15 lines from /Users/rafael/Library/Logs/Homebrew/gitsh/01.configure:
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:782:in `try_func'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
	from extconf.rb:44:in `<main>'
configure: error: Failed to configure Ruby extension

```
MacOS Somona Version 14.3

**Comment by mjc-gh** [comment]
Getting the same issue with homebrew on 

```
uname -a
Darwin host.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020 arm64
```

**Comment by serg94** [comment]
So during the install I have faced 2 issues: 
1. curses/ncurses didn't found
2. after fixing it I got `rl_completion_suppress_quote` not found in library `readline`

For the first issue just run this to install
`brew install ncurses`
`gem install curses -- --use-system-libraries --with-ncurses-dir=/usr/local/opt/ncurses`

download readline 8.1 from here https://ftp.gnu.org/gnu/readline/
unpack it, move to the dir and run the commands
`./configure`
`make`
`make install` 

after that I installed gitsh from the source. [instrctions here](https://github.com/thoughtbot/gitsh/blob/7b890ea6314cfc08a25f5a2c94322e5368a7ffa5/INSTALL#L77)



macOS 14.3.1
ruby --version -> ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
Terminal -> bash, without using Rosetta

**Comment by RafaelHovhannisyan** [comment]
Worked for me!!! Thanks

**Comment by mjc-gh** [comment]
@serg94 you're my hero! thanks!!
